### PR TITLE
support rails 5.1

### PR DESCRIPTION
**Pull request by grosser**
some warning about db-cleaner ... and 1 failure with fully_loaded :(

```
Testing with ActiveRecord 5.1.0

Randomized with seed 40711
DEPRECATION WARNING: schema_migrations_table_name is deprecated and will be removed from Rails 5.2 (called from block (2 levels) in <top (required)> at /Users/mgrosser/Code/tools/goldiloader/spec/spec_helper.rb:34)
...................................F.....................................

Failures:

  1) Goldiloader with fully_load true auto eager loads a has_many association when last is called
     Failure/Error: expect(blog.association(:posts_fully_load)).to be_loaded
       expected `#<ActiveRecord::Associations::HasManyAssociation:0x007fceea4b8cd0 @reflection=#<ActiveRecord::Reflect...l>, #<Post id: 2, title: "blog1-post2", blog_id: 1, author_id: 2, owner_type: nil, owner_id: nil>]>>.loaded?` to return true, got false
     # ./spec/goldiloader/goldiloader_spec.rb:681:in `block (4 levels) in <top (required)>'
     # ./spec/goldiloader/goldiloader_spec.rb:680:in `each'
     # ./spec/goldiloader/goldiloader_spec.rb:680:in `block (3 levels) in <top (required)>'

Finished in 5.09 seconds (files took 1.2 seconds to load)
73 examples, 1 failure

Failed examples:

rspec ./spec/goldiloader/goldiloader_spec.rb:676 # Goldiloader with fully_load true auto eager loads a has_many association when last is called

```

### CODE REVIEW

**Comment by grosser** [comment]
@jturkel

**Comment by grosser** [comment]
stupid coveralls won't shut up :D 

... use https://github.com/grosser/single_cov ;)

**Comment by jturkel** [comment]
That was as far as I made it with Rails 5.1 compatibility too :)

It looks like the methods affected by the `fully_load` setting were removed from `ActiveRecord::Associations::CollectionAssociation` in https://github.com/rails/rails/pull/26200. I have branch (https://github.com/salsify/goldiloader/compare/feature/rails-5-1) that gets things working again. I should be able to get it landed in the next few days.

**Comment by jturkel** [comment]
Closing in favor of #48 which addresses the issue with `fully_loaded`.

**Pull request closed without merging**
